jbosstools/jbosstools-server

as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/core/server/UnitedServerListenerManager.java

Isolated some synchronizes a bit further to further decrease chance of deadlock
Isolated some synchronizes a bit further to further decrease chance of deadlock
Added comments for clarity
Added comments for clarity
JBIDE-19376 - fixes as per fred's suggestion of CopyOnWriteArrayList.  Still need a few synchronizes though to ensure we know when we initialized
JBIDE-19376 - fixes as per fred's suggestion of CopyOnWriteArrayList.  Still need a few synchronizes though to ensure we know when we initialized

JBIDE-19376 - deadlock caused by UnitedServerListenerManager implementation

---

as/plugins/org.jboss.ide.eclipse.as.management.as71/src/org/jboss/ide/eclipse/as/internal/management/as71/AS71Manager.java
as/plugins/org.jboss.ide.eclipse.as.management.as71/src/org/jboss/ide/eclipse/as/internal/management/as71/DeploymentOperationResult.java
as/plugins/org.jboss.ide.eclipse.as.management.wildfly8/src/org/jboss/ide/eclipse/as/internal/management/wildfly8/DeploymentOperationResult.java
as/plugins/org.jboss.ide.eclipse.as.management.wildfly8/src/org/jboss/ide/eclipse/as/internal/management/wildfly8/Wildfly8Manager.java
as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/wtp/core/server/publish/LocalZippedModulePublishRunner.java

and that progress monitor more accurately represents progress.

JBIDE-19350 - ensure mgmt publishing is cancelable at more locations,

---

as/plugins/org.jboss.tools.as.runtimes.integration/src/org/jboss/tools/as/runtimes/integration/ui/composites/DownloadRuntimeHomeComposite.java

https://issues.jboss.org/browse/JBIDE-19637
Runtime download not working from New Server dialog

JBIDE-19637 - Runtime download not working from New Server dialog

---

jmx/plugins/org.jboss.tools.jmx.core/src/org/jboss/tools/jmx/core/tree/MBeansNode.java
jmx/plugins/org.jboss.tools.jmx.ui/src/org/jboss/tools/jmx/ui/internal/actions/RefreshAction.java
jmx/plugins/org.jboss.tools.jmx.ui/src/org/jboss/tools/jmx/ui/internal/views/navigator/MBeanExplorerContentProvider.java

This reverts commit 090b7b3dc20a0aa45a47a5f6d7d3b00627a18bef.

Revert "JBIDE-20188 - refresh action does not preserve expansion / selection"

---

jmx/plugins/org.jboss.tools.jmx.core/src/org/jboss/tools/jmx/core/tree/MBeansNode.java
jmx/plugins/org.jboss.tools.jmx.ui/src/org/jboss/tools/jmx/ui/internal/actions/RefreshAction.java
jmx/plugins/org.jboss.tools.jmx.ui/src/org/jboss/tools/jmx/ui/internal/actions/RefreshActionState.java
jmx/plugins/org.jboss.tools.jmx.ui/src/org/jboss/tools/jmx/ui/internal/views/navigator/MBeanExplorerContentProvider.java

JBIDE-20188 - missing file caused compilation errors

JBIDE-20188 - refresh action does not preserve expansion / selection

---

jmx/plugins/org.jboss.tools.jmx.jvmmonitor.ui/src/org/jboss/tools/jmx/jvmmonitor/internal/ui/properties/memory/HeapComparator.java

Fix deligates long comparison to Long.compare() method.

JBIDE-20748 "Comparison method violates its general contract!"

---

as/plugins/org.jboss.ide.eclipse.as.wtp.ui/src/org/jboss/ide/eclipse/as/wtp/ui/prompt/ZombieProcessPrompter.java

JBIDE-21470 - MessageBox changed to MessageDialog in

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/tools/as/core/internal/modules/ModuleDeploymentPrefsUtil.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/tools/as/core/server/controllable/subsystems/internal/StandardFileSystemPublishController.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/tools/as/core/server/controllable/systems/AbstractJBossDeploymentOptionsController.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/tools/as/core/server/controllable/systems/IDeploymentZipOptionsController.java
as/plugins/org.jboss.ide.eclipse.as.ui/jbossui/org/jboss/ide/eclipse/as/ui/editor/ModuleDeploymentOptionsComposite.java
as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/core/util/IJBossToolingConstants.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/internal/MockPublishMethodFilesystemController.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/internal/utils/ServerParameterUtils.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/parametized/server/publishing/AbstractPublishingTest.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/parametized/server/publishing/defect/PerModuleZipTest.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/parametized/server/publishing/defect/PublishDefectSuite.java

Initial implementation for some testing and feedback @mmalina

JBIDE-22157 - per-module zip settings

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/launch/CommandLineLaunchConfigProperties.java
as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/RSEJBoss7LaunchConfigurator.java
as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/RSEJbossLaunchConstants.java
as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/RSELaunchConfigProperties.java
as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/StandardRSEJBossStartLaunchDelegate.java
as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/StandardRSEStartLaunchDelegate.java
as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/subsystems/RSECommandLineLaunchController.java
as/plugins/org.jboss.ide.eclipse.as.rse.ui/plugin.xml
as/plugins/org.jboss.ide.eclipse.as.rse.ui/src/org/jboss/ide/eclipse/as/rse/ui/editor/DebugPortSection.java
as/plugins/org.jboss.ide.eclipse.as.ui/jbossui/org/jboss/ide/eclipse/as/ui/editor/PortSection.java
as/plugins/org.jboss.ide.eclipse.as.ui/schema/ServerEditorPortSection.exsd
as/plugins/org.jboss.ide.eclipse.as.wtp.core/.settings/org.eclipse.jdt.core.prefs
as/plugins/org.jboss.ide.eclipse.as.wtp.core/META-INF/MANIFEST.MF
as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/wtp/core/debug/RemoteDebugUtils.java

Fix bug where always using default port, never user-specified

JBIDE-9442 - Add remote debugger launch when running server via rse

---

as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/wtp/core/Messages.java
as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/wtp/core/Messages.properties
as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/wtp/core/server/launch/ServerProcess.java

- Add fake process for non process launches

[JBIDE-22152] - Server Adapter, Debugging: Unknown launch is left in Debug view after deletion of an OS 3 server adapter

---

as/plugins/org.jboss.ide.eclipse.as.ui/jbossui/org/jboss/ide/eclipse/as/ui/actions/AbstractServerActionDelegate.java

JBIDE-23758 - Return empty Selection instead of null

---

jmx/plugins/org.jboss.tools.jmx.jolokia/.classpath
jmx/plugins/org.jboss.tools.jmx.jolokia/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.jolokia/build.properties
jmx/plugins/org.jboss.tools.jmx.jolokia/pom.xml
jmx/pom.xml
jmx/tests/org.jboss.tools.jmx.jolokia.test/.classpath
jmx/tests/org.jboss.tools.jmx.jolokia.test/META-INF/MANIFEST.MF
jmx/tests/org.jboss.tools.jmx.jolokia.test/build.properties
jmx/tests/org.jboss.tools.jmx.jolokia.test/pom.xml

This PR won't build  yet. I've had to ask Roland Huss to create a snapshot.   http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jolokia%22  doesn't have any snapshots listed.

JBIDE-23869 - consume jolokia snapshot with our classcast fix

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/tools/as/core/server/controllable/profile/internal/LocalManagementProfileInitializer.java
as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/subsystems/RSEManagementProfileInitializer.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/subsystems/DefaultPollerResolutionTest.java

Test case for the poller issue.

JBIDE-24520 - unit test for eap7+ pollers

---

as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/wtp/core/server/behavior/LocalFilesystemController.java

top 1 from AERI. Over 500 reports

jbide-24541: unable to delete resource exception in LocalFilesystemController

---

all-itests/pom.xml
as/itests/org.jboss.tools.as.management.itests/pom.xml

add itests-only pom for running just the itests; fix missing version
Signed-off-by: nickboldt <nboldt@redhat.com>

add itests-only pom for running just the itests; fix missing version

---

as/itests/pom.xml
as/plugins/org.jboss.ide.eclipse.as.management.wf11/.classpath
as/plugins/org.jboss.ide.eclipse.as.management.wf11/META-INF/MANIFEST.MF
as/plugins/org.jboss.ide.eclipse.as.management.wf11/build.properties
as/plugins/org.jboss.ide.eclipse.as.management.wf11/pom.xml
as/plugins/org.jboss.ide.eclipse.as.management.wf11/src/org/jboss/ide/eclipse/as/internal/management/wf11/WildFly11Manager.java

JBIDE-24521 - large files in deployment to wf11 beta

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/extensions/descriptors/XMLDocumentRepository.java

JBIDE-24894 - fix for NPE that causes regressions

---

as/test-framework/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/requirement/ServerRequirement.java

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

Adapt JBoss ServerRequrement to RedDeer 2 final.

---

as/plugins/org.jboss.ide.eclipse.as.management.wf11/META-INF/MANIFEST.MF
as/plugins/org.jboss.ide.eclipse.as.management.wf11/pom.xml

JBIDE-25270 - update mgmt jars to eap 7.1 cr3

---

jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/JolokiaConnectionWrapper.java
jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaMBeanServerConnection.java
jmx/tests/org.jboss.tools.jmx.jolokia.test/src/org/jboss/tools/jmx/jolokia/test/internal/connection/JolokiaMBeanServerConnectionGetDomainsTest.java
jmx/tests/org.jboss.tools.jmx.jolokia.test/src/org/jboss/tools/jmx/jolokia/test/internal/connection/JolokiaMBeanServerConnectionGetSetAttributeTest.java
jmx/tests/org.jboss.tools.jmx.jolokia.test/src/org/jboss/tools/jmx/jolokia/test/internal/connection/JolokiaMBeanServerConnectionInvocationTest.java
jmx/tests/org.jboss.tools.jmx.jolokia.test/src/org/jboss/tools/jmx/jolokia/test/internal/connection/JolokiaMBeanServerConnectionMBeanInfoTest.java
jmx/tests/org.jboss.tools.jmx.jolokia.test/src/org/jboss/tools/jmx/jolokia/test/internal/connection/JolokiaMBeanServerConnectionQueryMBeansTest.java
jmx/tests/org.jboss.tools.jmx.jolokia.test/src/org/jboss/tools/jmx/jolokia/test/internal/connection/JolokiaMBeanServerGetAttributeWithConvertedTypeTest.java
jmx/tests/org.jboss.tools.jmx.jolokia.test/src/org/jboss/tools/jmx/jolokia/test/util/JolokiaTestEnvironmentSetup.java

I recommend to review and merge https://github.com/jbosstools/jbosstools-server/pull/549 before reviewing this PR

Jbide 25429 respect get post request type

---

as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/parametized/server/publishing/defect/PublishWeb2DeletesWeb1LibsTest.java

- factorize code
- use List instead of Array to simplify code
- add the teardown to clean projects at end of execution
- remove JUnit3 dependency
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Fix technical debt

---

as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/SingleDeployableFileTest.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/tools/as/core/server/controllable/subsystems/internal/StandardFileSystemPublishController.java

Fix two failing itests

---

as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/wtp/core/server/publish/BinaryModulePublishRunner.java

current implementation for incremental publishing will *NOT* update folders. It is only transferring files in the root folder.

[JBIDE-25303] incremental publish for binary modules publishes folders

---

as/plugins/org.jboss.ide.eclipse.as.management.wf11/.classpath
as/plugins/org.jboss.ide.eclipse.as.management.wf11/META-INF/MANIFEST.MF
as/plugins/org.jboss.ide.eclipse.as.management.wf11/pom.xml

JBIDE-24111 - update to eap 7.1 final jars

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.xml

JBIDE-25578 - allow java9 facet

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/reddeer/util/DeployJSPProjectTemplate.java
as/test-framework/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/editor/AbstractEditorWithBrowser.java

JBIDE-25604 Added WildFly 11 and EAP 7.1 in test suite

---

jmx/plugins/org.jboss.tools.jmx.jolokia/.classpath
jmx/plugins/org.jboss.tools.jmx.jolokia/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.jolokia/pom.xml

JBIDE-25614 - upgrade jolokia client

---

jmx/plugins/org.jboss.tools.jmx.jolokia/build.properties

JBIDE-25614 - build.properties not updated for upgraded jolokia

---

as/itests/org.jboss.tools.as.ui.bot.itests/pluginCustomization.ini
as/itests/org.jboss.tools.as.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/download/RuntimeDownloadTestUtility.java
as/itests/pom.xml

org.jboss.tools.as.ui.bot.itests

JBIDE-25694 Parameters for tests added in pom for

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/extendedproperties/JBossEAP70DefaultLaunchArguments.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/extendedproperties/JBossEAP71ExtendedProperties.java

JBDS-4678 - ensure memory args are correct for eap 7.0+

---

as/test-framework/org.jboss.ide.eclipse.as.reddeer/META-INF/MANIFEST.MF
as/test-framework/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/deploy/DeployOnServer.java

JBIDE-25815 Fixes DeployOnServer class for Forge ITests on Jenkins

---

jmx/features/org.jboss.tools.jmx.feature/feature.xml
jmx/features/org.jboss.tools.jmx.feature/pom.xml
jmx/features/org.jboss.tools.jmx.test.feature/feature.xml
jmx/features/org.jboss.tools.jmx.test.feature/pom.xml
jmx/features/pom.xml
jmx/plugins/org.jboss.tools.jmx.core/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.core/pom.xml
jmx/plugins/org.jboss.tools.jmx.jolokia/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.jolokia/pom.xml
jmx/plugins/org.jboss.tools.jmx.jvmmonitor.core/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.jvmmonitor.core/pom.xml
jmx/plugins/org.jboss.tools.jmx.jvmmonitor.tools/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.jvmmonitor.tools/pom.xml
jmx/plugins/org.jboss.tools.jmx.jvmmonitor.ui/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.jvmmonitor.ui/pom.xml
jmx/plugins/org.jboss.tools.jmx.local/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.local/pom.xml
jmx/plugins/org.jboss.tools.jmx.ui/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.ui/pom.xml
jmx/plugins/pom.xml
jmx/pom.xml
jmx/tests/org.jboss.tools.jmx.core.test/META-INF/MANIFEST.MF
jmx/tests/org.jboss.tools.jmx.core.test/pom.xml
jmx/tests/org.jboss.tools.jmx.jolokia.test/META-INF/MANIFEST.MF
jmx/tests/org.jboss.tools.jmx.jolokia.test/pom.xml
jmx/tests/org.jboss.tools.jmx.ui.test/META-INF/MANIFEST.MF
jmx/tests/org.jboss.tools.jmx.ui.test/pom.xml
jmx/tests/pom.xml

[JBIDE-25947] - Adapt server for Photon

---

jmx/tests/org.jboss.tools.jmx.jolokia.test/META-INF/MANIFEST.MF

[JBIDE-25947] - Adapt server for Photon (#570)

---

as/plugins/org.jboss.ide.eclipse.as.classpath.core/src/org/jboss/ide/eclipse/as/classpath/core/runtime/jbossmodules/internal/JBossModulesDefaultClasspathModel.java
as/plugins/org.jboss.ide.eclipse.as.ui/jbossui/org/jboss/ide/eclipse/as/ui/wizards/JBInitialSelectionProvider.java

JBIDE-26016 - make sure websocket api is available for wf12

---

as/plugins/org.jboss.ide.eclipse.as.ui/jbossui/org/jboss/ide/eclipse/as/ui/views/server/extensions/ShowInWelcomePageActionProvider.java

JBIDE-26019 - fix thread access error

---

archives/tests/org.jboss.ide.eclipse.archives.ui.test/META-INF/MANIFEST.MF

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

JBIDE-26034: Add wst.server.ui dependency to archives ui tests.

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.xml

[JBIDE-26157] - Support for JEE8 projects

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.xml

[JBIDE-26157] - JEE8 cleanup

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/reddeer/ui/RuntimeDetectionPreferencePage.java

JBIDE-26227 Fixing condition for RuntimeDetectionPreferencePage

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/AbstractTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/archives/VariousProjectsArchiving.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/RuntimeDetectionDuplicatesTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimesTest.java

JBIDE-26325 Server Itests stabilization and adding new servers in

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/JBossLaunchAdapter.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/JBossServer.java

#586 - NPEs while creating server adapter on the fly

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.properties

JBIDE-26307 - rename eap 7.1 to 7.x

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

JBIDE-26436 add WF14 in ITests suites

---

as/plugins/org.jboss.tools.as.catalog/plugin.xml
as/plugins/org.jboss.tools.as.catalog/schema/xsd/.gitignore
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-app_8_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-client_8_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-common_7_1.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-common_8_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss_7_0.xsd
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/catalog/CatalogMissingEntriesTest.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/catalog/CatalogValidationTest.java

- Add jboss-common and other missing files

[JBIDE-26384] - Add "jboss-web_12_1.xsd" and others

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/JMXAllTests.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/JMXUITest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/local/connection/JMXLocalConnectionTest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/JMXServerConnectionAutoDeployDisableTest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/JMXServerConnectionTest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/JMXServerTestTemplate.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/RemoteServerJMXConnectionTest.java
as/test-framework/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/requirement/RemoteServerConfiguration.java
as/test-framework/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/requirement/ServerRequirement.java
jmx/test-framework/org.jboss.tools.jmx.reddeer/src/org/jboss/tools/jmx/reddeer/core/JMXConnectionItem.java

- Adding new RemoteServerJMXConnectionTest class

JBIDE-26440 - New remote server JMX connection test

---

as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/TestConstants.java

JBIDE-26450 Fix typo in tests for WildFly 14

---

as/itests/org.jboss.tools.as.management.itests/META-INF/MANIFEST.MF
as/itests/org.jboss.tools.as.management.itests/src/org/jboss/tools/as/management/itests/JBossManagementServiceTest.java

JBIDE-26519 Replace org.eclipse.equinox.ds for org.apache.felix.scr

---

as/itests/pom.xml

JBIDE-26545 Update download URL for eap 7

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

JBIDE-26554 Add WildFly 15 in ITests suites

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.xml

JBIDE-26570: WildFly 15 and 16 do not allow JEE8 deployments

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/projects/RunApp.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/JMXTestTemplate.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/JMXUITest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/local/connection/JMXLocalConnectionTest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/JMXServerConnectionAutoDeployDisableTest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/JMXServerConnectionTest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/JMXServerTestTemplate.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/RemoteServerJMXConnectionTest.java
jmx/test-framework/org.jboss.tools.jmx.reddeer/src/org/jboss/tools/jmx/reddeer/core/JMXConnection.java
jmx/test-framework/org.jboss.tools.jmx.reddeer/src/org/jboss/tools/jmx/reddeer/core/JMXConnectionExists.java
jmx/test-framework/org.jboss.tools.jmx.reddeer/src/org/jboss/tools/jmx/reddeer/core/JMXConnectionItem.java

- run tests for eap 7.2 and wildfly 16 servers

Update jmx tests to use EAP-7.2

---

as/itests/pom.xml
as/plugins/org.jboss.tools.as.catalog/plugin.xml
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-remoting_5_1.xsd

JBIDE-26666: Switch from WF17.Beta to WF17

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/extendedproperties/JBoss70DefaultLaunchArguments.java

[621] Fix incorrect java import

---

as/plugins/org.jboss.ide.eclipse.as.ui/jbossui/org/jboss/ide/eclipse/as/ui/editor/ModuleDeploymentOptionsComposite.java

adding a setter to select the deployment type filter combo

[JBIDE-26694] allow consumers to set the deployment type filter

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/launchers/JMXAllTests.launch
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json

Extend jmx testing with wf17

---

as/itests/org.jboss.tools.as.ui.bot.itests/META-INF/MANIFEST.MF
as/itests/org.jboss.tools.as.ui.bot.itests/build.properties
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

JBIDE-26675 Update server ITests to use WF17

---

as/itests/pom.xml

JBDS-4782 Fix profile name to avoid downloading unnecessary runtimes

---

pom.xml

JBIDE-26798 Switch repo URL from http to https

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

Build: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/job/server.it.weekly.jkopriva/694/jdk=jdk1.8,label_exp=rhel7/

Add WF18 in suites

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/JMXTestTemplate.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/JMXServerConnectionTest.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/JMXServerTestTemplate.java
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/src/org/jboss/tools/as/jmx/ui/bot/itests/server/connection/RemoteServerJMXConnectionTest.java
jmx/test-framework/org.jboss.tools.jmx.reddeer/src/org/jboss/tools/jmx/reddeer/core/JMXConnection.java

Update jmx tests to use newer WF

---

as/itests/org.jboss.tools.as.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/EAPTestsSuite.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/server/SingleServerAdaptersTest.java

JBIDE-26949 Add Server Adapter tests in single runtime suite(for EAP QE

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
pom.xml

[Chore] Fix build warnings

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.properties

JBIDE-26988: Mark old EAP runtimes not fully supported anymore

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/util/ServerNamingUtility.java

Ensure end of life flag does not become part of server name

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/download/InvalidCredentialProductDownloadTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

JBIDE-27088 Fix Server ITests server names

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/DeployableServer.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/util/ServerNamingUtility.java

Shorten EAP in default server name, avoid wtp default names

---

as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/RSEStreamsProxy.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=558489 for upstream
issue

JBIDE-27142: fix compile issue

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.properties

Fixes JBIDE-27143 - Remove tech preview from eap 7.3

---

as/itests/pom.xml

JBIDE-27143: add EAP 7.3 support

---

as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/TestConstants.java

Green build: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CodeReady%20Studio%20QE/job/Studio/job/Quality/job/Integration-tests/job/server-management-itests/25/

JBIDE-27190 Fix server constants

---

as/itests/pom.xml
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/parametized/server/ServerBeanLoader3Test.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/parametized/server/ServerBeanRuntimeMatcherTest.java

JBIDE-27191 Update ITests to use WF19 Final instead of Beta

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/reddeer/util/OperateServerTemplate.java

EAP 7.3 Itests fix

---

as/itests/org.jboss.tools.as.ui.bot.itests/pom.xml

JBIDE-27269 Update default parameters for EAP ITests profile

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

JBIDE-27268 EAP 7.3.0 Label fix, add WF19 in test suites.

---

as/plugins/org.jboss.ide.eclipse.as.classpath.core/src/org/jboss/ide/eclipse/as/classpath/core/runtime/cache/internal/ModuleAliasUtil.java
as/plugins/org.jboss.ide.eclipse.as.classpath.core/src/org/jboss/ide/eclipse/as/classpath/core/runtime/cache/internal/ModuleSlot.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/classpath/modules/ModuleSlotStackOverflowDefectTest.java

JBIDE-27245 - fix stack overflow in module classpath, add test case

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/META-INF/MANIFEST.MF
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/subsystems/PublishRunnerTest.java
jmx/test-framework/org.jboss.tools.jmx.reddeer/META-INF/MANIFEST.MF

JBIDE-27301: fix RedDeer dependencies

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json
as/itests/pom.xml
jmx/test-framework/org.jboss.tools.jmx.reddeer/src/org/jboss/tools/jmx/reddeer/core/JMXConnectionItem.java

https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/jmx-itests/14/

JBIDE-27294 Update/Refactoring of JMX ITests POM

---

as/plugins/org.jboss.ide.eclipse.as.management.core/src/org/jboss/ide/eclipse/as/management/core/JBoss7ServerState.java
as/tests/org.jboss.tools.as.test.core/META-INF/MANIFEST.MF
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/management/JBoss7ServerStateTest.java

Fixes JBIDE-27308 - error in server state enums, no test ever created

---

as/itests/org.jboss.tools.as.management.itests/src/org/jboss/tools/as/management/itests/utils/ParameterUtils.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/PomServerConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

JBIDE-27319 Add WF20 in ITests suites

---

as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/internal/utils/ServerParameterUtils.java

Build: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/server-as-itests/11/

JBIDE-27352 Update parameters for tests after last changes

---

README.md
as/itests/org.jboss.tools.as.management.itests/src/org/jboss/tools/as/management/itests/utils/JREParameterUtils.java
as/itests/org.jboss.tools.as.management.itests/src/org/jboss/tools/as/management/itests/utils/StartupUtility.java
as/itests/org.jboss.tools.as.ui.bot.itests/launchers/AllTestsSuite.launch
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimesTest.java
as/itests/pom.xml
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/TestConstants.java
wtp/itests/org.jboss.tools.wtp.runtimes.tomcat.itests/pom.xml
wtp/itests/org.jboss.tools.wtp.runtimes.tomcat.itests/src/org/jboss/tools/wtp/runtimes/tomcat/itests/AbstractTomcatDetectionTest.java
wtp/itests/org.jboss.tools.wtp.runtimes.tomcat.itests/src/org/jboss/tools/wtp/runtimes/tomcat/itests/ServerUtilTest.java
wtp/itests/org.jboss.tools.wtp.runtimes.tomcat.itests/src/org/jboss/tools/wtp/runtimes/tomcat/itests/TomcatDetectionTest.java
wtp/plugins/org.jboss.tools.wtp.runtimes.tomcat/src/org/jboss/tools/wtp/runtimes/tomcat/internal/detection/TomcatRuntimeDetectorDelegate.java

JBIDE-27320 Remove old JRE from server parameters(4, 5, 6 and 7)

---

as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/classpath/ClasspathSuite.java

JBIDE-27245 Add ModuleSlotStackOverflowDefectTest in suite

---

as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/extendedproperties/JBossEAP72DefaultLaunchArguments.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/extendedproperties/JBossEAP73DefaultLaunchArguments.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/extendedproperties/Wildfly150DefaultLaunchArguments.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/launch/configuration/JBossLaunchConfigProperties.java
as/plugins/org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/internal/v7/LocalJBoss7StartConfigurator.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/utiltests/ArgsUtilTest.java

JBIDE-26602 - fix vm args when changing vm between j8 and j11

---

archives/tests/org.jboss.ide.eclipse.archives.ui.test/src/org/jboss/ide/eclipse/archives/ui/test/bot/ArchivesTestBase.java

Fix archive test failures 

---

as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/TestConstants.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/internal/utils/ServerParameterUtils.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/parametized/server/ServerBeanRuntimeMatcherTest.java

Build: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/server-as-itests/36/

WF21 As ITests fix

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

Update parameters in ITests to use WF 21 Beta1

---

as/plugins/org.jboss.ide.eclipse.as.rse.core/src/org/jboss/ide/eclipse/as/rse/core/RSEJBoss7LaunchConfigurator.java

Fixes debugging app server running on remote system post java9

---

as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyArchivePathVarNestedWarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyArchivePathVarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyArchivePathVarWarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyExternalArchiveVarNestedWarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyExternalArchiveVarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyExternalArchiveVarWarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyWorkspaceArchiveVarNestedWarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyWorkspaceArchiveVarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/DeploymentAssemblyWorkspaceArchiveVarWarTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/RepublishDefectTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/SingleDeployableFileTest.java
as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/server/publishing/SingleDeployableFolderTest.java

Green Build: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/server-as-itests/42/jdk=openjdk-11,label=rhel8-medium/

JBIDE-26526 Add parameters names in ITests

---

as/plugins/org.jboss.tools.as.catalog/plugin.xml
as/plugins/org.jboss.tools.as.catalog/schema/xsd/elytron-client-1_6.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-as-infinispan_10_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-as-infinispan_11_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-as-infinispan_4_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-as-infinispan_6_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-as-infinispan_7_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-as-infinispan_8_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-as-infinispan_9_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-ejb-client_1_4.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/web-app_4_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/web-common_4_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/web-facelettaglibrary_2_3.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/web-fragment_4_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/web-partialresponse_2_3.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-config_14_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-ejb3_8_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-elytron_11_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-messaging-activemq_11_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-microprofile-fault-tolerance-smallrye_1_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-microprofile-jwt-smallrye_1_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-microprofile-openapi-smallrye_1_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-microprofile-opentracing_3_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-undertow_11_0.xsd

Updated catalog for wf21

---

archives/tests/org.jboss.ide.eclipse.archives.ui.test/pom.xml

JBIDE-27407 Add skipITests in Archives UI Tests POM

---

archives/test-framework/org.jboss.tools.archives.reddeer/src/org/jboss/tools/archives/reddeer/archives/ui/ProjectArchivesExplorer.java
archives/test-framework/org.jboss.tools.archives.reddeer/src/org/jboss/tools/archives/reddeer/archives/ui/ProjectArchivesView.java
archives/test-framework/org.jboss.tools.archives.reddeer/src/org/jboss/tools/archives/reddeer/component/Archive.java
archives/test-framework/org.jboss.tools.archives.reddeer/src/org/jboss/tools/archives/reddeer/component/ArchiveProject.java
archives/test-framework/org.jboss.tools.archives.reddeer/src/org/jboss/tools/archives/reddeer/component/Fileset.java
archives/test-framework/org.jboss.tools.archives.reddeer/src/org/jboss/tools/archives/reddeer/component/Folder.java
archives/test-framework/org.jboss.tools.archives.reddeer/src/org/jboss/tools/archives/reddeer/component/UserLibraryFileset.java
archives/tests/org.jboss.ide.eclipse.archives.ui.test/src/org/jboss/ide/eclipse/archives/ui/test/bot/ArchivesTestBase.java

Add activate in archives.reddeer to stabilize tests

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json
as/itests/pom.xml

https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/jmx-itests/142/testReport/

JBIDE-27594 JMX ITests updates

---

as/plugins/org.jboss.tools.as.catalog/plugin.xml
as/plugins/org.jboss.tools.as.catalog/schema/xsd/jboss-as-infinispan_9_1.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-config_15_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-elytron_12_0.xsd
as/plugins/org.jboss.tools.as.catalog/schema/xsd/wildfly-messaging-activemq_12_0.xsd

JBIDE-27600: update schemas for Widlfly 22.0.0.Beta1

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/PomServerConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
as/itests/pom.xml

JBIDE-27593 AS ITests fixes

---

archives/features/pom.xml
as/features/pom.xml
jmx/features/pom.xml
wtp/features/pom.xml

JBIDE-27614: fix source feature generation

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json

JBIDE-27717 JMX ITests updates

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.properties

Adds tech preview label

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/PomServerConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
as/itests/pom.xml

JBIDE-27711 Variable updates in ITests

---

test-pr-file.txt

Testing PR, reverting commited file

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/PomServerConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
as/itests/pom.xml

JBIDE-27906 WF24 Itests fixes

---

.gitignore
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/AllTestsSuite.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/SmokeTestsSuite.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ShowInContextMenuTest.java

ShowInBrowserTest and SmokeTestsSuite added

ShowInBrowser Test

---

as/itests/org.jboss.tools.as.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.ui.bot.itests/requirements/wildfly-requirement.json

@odockal @jkopriva Added maven profile for Jenkins job and wildfly requirement file.

New maven profile and wildfly requirement

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.properties

JBIDE-28006 Fix typo in server adapter for EAP 7.4

---

as/itests/org.jboss.tools.as.management.itests/src/org/jboss/tools/as/management/itests/utils/ParameterUtils.java
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/internal/utils/ServerParameterUtils.java

Remove WF22 from test suites

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json

JBIDE-28012 Update JMX ITests to the latest runtimes

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/PomServerConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
as/itests/pom.xml

Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>

JBIDE-28194: Update wildfly version to 25

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/SmokeTestsSuite.java

@olkornii
Added ServerRuntimesTest and ServerAdaptersTest to SmokeTestsSuite

Adding test classes to SmokeTestsSuite

---

as/itests/org.jboss.tools.as.management.itests/META-INF/MANIFEST.MF

JBIDE-28051: update mockito dependency

---

as/itests/org.jboss.tools.as.ui.bot.itests/requirements/jre.json
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/PomServerConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ShowInContextMenuTest.java
as/itests/pom.xml
as/test-framework/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/preferences/WebBrowserPreferencePage.java
as/test-framework/org.jboss.ide.eclipse.as.reddeer/src/org/jboss/ide/eclipse/as/reddeer/server/requirement/InternalBrowserRequirement.java

Add WildFly 26 server and include other UI tests fixes and patches

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.jmx.ui.bot.itests/resources/requirements.json

Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>

update WF versions for jmx-itests

---

as/itests/org.jboss.tools.as.ui.bot.itests/requirements/wildfly-requirement.json

Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>

fixed WF requirement for server-itest

---

as/itests/org.jboss.tools.as.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/server/SingleServerRuntimeTest.java

Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>
https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/server-eap-itests/109/jdk=openjdk-11,label=rhel8/

updated eap7.3 to eap7.4

---

jmx/plugins/org.jboss.tools.jmx.jolokia/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.jolokia/build.properties
jmx/plugins/org.jboss.tools.jmx.jolokia/pom.xml
jmx/tests/org.jboss.tools.jmx.jolokia.test/META-INF/MANIFEST.MF
jmx/tests/org.jboss.tools.jmx.jolokia.test/build.properties
jmx/tests/org.jboss.tools.jmx.jolokia.test/pom.xml
jmx/tests/org.jboss.tools.jmx.jolokia.test/src/org/jboss/tools/jmx/jolokia/test/util/JolokiaTestEnvironmentSetup.java

JBIDE-28501: fix tests after TP update

---

archives/tests/org.jboss.ide.eclipse.archives.ui.test/src/org/jboss/ide/eclipse/archives/ui/test/bot/CreatingArchiveTest.java

CreatingArchiveTest control focus bug fix

---

archives/features/org.jboss.ide.eclipse.archives.feature/feature.xml
jmx/features/org.jboss.tools.jmx.test.feature/feature.xml

JBIDE-28477: fix after update to latest 4.25.0.AM1 parent

---

as/itests/org.jboss.tools.as.jmx.ui.bot.itests/META-INF/MANIFEST.MF

Signed-off-by: Lukas Grossmann <lgrossma@redhat.com>

Fixing MANIFEST.MF file for tests to run

---

as/itests/org.jboss.tools.as.management.itests/META-INF/MANIFEST.MF
as/tests/org.jboss.tools.as.test.core/META-INF/MANIFEST.MF
as/tests/org.jboss.tools.as.test.core/src/org/jboss/tools/as/test/core/utiltests/ServerHomeValidationUtilityTest.java
jmx/tests/org.jboss.tools.jmx.jolokia.test/META-INF/MANIFEST.MF

JBIDE-28815: Fix after TP update

---

as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimesTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/reddeer/util/OperateServerTemplate.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/server/SingleServerRuntimeTest.java
as/itests/pom.xml

+ speed up tests by small changes

server-itests + server-eap-itests fixes

---

as/itests/org.jboss.tools.as.itests/src/org/jboss/tools/as/itests/ProjectRuntimeClasspathTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/requirements/jre.json
as/itests/org.jboss.tools.as.ui.bot.itests/requirements/wildfly-requirement.json
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/AbstractTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/archives/DeployingArchiveTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/archives/VariousProjectsArchiving.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/PomServerConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerActualJavaTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimesTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ShowInContextMenuTest.java
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/server/SingleServerAdaptersTest.java
as/itests/pom.xml

Updates for server-itests / fixes / removed wf25

Wf27 update

---

as/itests/org.jboss.tools.as.ui.bot.itests/pom.xml
as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java

Jbide 28867

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.xml

Fixes JBIDE-28842 - web facet 6, for fred

---

as/plugins/org.jboss.ide.eclipse.as.wtp.core/src/org/jboss/ide/eclipse/as/wtp/core/ASWTPToolsPlugin.java
jmx/plugins/org.jboss.tools.jmx.ui/META-INF/MANIFEST.MF
jmx/plugins/org.jboss.tools.jmx.ui/src/org/jboss/tools/jmx/ui/internal/actions/MBeanServerConnectAction.java

Fixes #793 - add telemetry for missing feature-parity features

---

as/plugins/org.jboss.ide.eclipse.as.core/plugin.xml

Fixes JBIDE-29032 - eap 7.4 needs updated facet support through java 17

---

site/category.xml

JBIDE-29177: add RSP feature in site
